export const SET_MESSAGE = "SET_MESSAGE";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_USERS = "SET_USERS";
export const SET_USERS_PAGINATION_CONFIG = "SET_USERS_PAGINATION_CONFIG";

// async

export const GET_ALL_USERS_STATS_SAGA = "GET_ALL_USERS_STATS_SAGA";
export const UPDATE_COUNTRY_FOR_USER_SAGA = "UPDATE_COUNTRY_FOR_USER_SAGA";
