export const SET_MESSAGE = "SET_MESSAGE";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const RESET_INITIAL_LOGIN_STATE = "RESET_INITIAL_LOGIN_STATE";

// async
export const LOGIN_SAGA = "LOGIN_SAGA";
export const VALIDATE_TOKEN_SAGA = "VALIDATE_TOKEN_SAGA";
export const LOGOUT_SAGA = "LOGOUT_SAGA";
