export const SET_ADMIN_SETTINGS_IS_LOADING = "SET_ADMIN_SETTINGS_IS_LOADING";
export const RESET_INITIAL_ADMIN_SETTINGS_STATE =
  "RESET_INITIAL_ADMIN_SETTINGS_STATE";
export const SET_ADMIN_SETTINGS_LIST = "SET_ADMIN_SETTINGS_LIST";

// async

export const GET_ADMIN_SETTINGS_LIST_SAGA = "GET_ADMIN_SETTINGS_LIST_SAGA";
export const SWITCH_ADMIN = "SWITCH_ADMIN";
