export const SET_MESSAGE = "SET_MESSAGE";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_TEAM_SETTINGS = "SET_TEAM_SETTINGS";

// async

export const GET_TEAM_SETTINGS_SAGA = "GET_TEAM_SETTINGS_SAGA";
export const UPDATE_TEAM_SETTINGS_SAGA = "UPDATE_TEAM_SETTINGS_SAGA";
