export const SET_SELECTED_NAV_SECTION = "SET_SELECTED_NAV_SECTION";
export const RESET_INITIAL_ROOT_STATE = "RESET_INITIAL_ROOT_STATE";
export const SET_CHEERS_STAT = "SET_CHEERS_STAT";

// async

export const GET_CHEERS_STAT = "GET_CHEERS_STAT";
