export const SET_REWARDS_IS_LOADING = "SET_REWARDS_IS_LOADING";
export const RESET_INITIAL_REWARDS_STATE = "RESET_INITIAL_REWARDS_STATE";
export const SET_SELECTED_SECTION_FOR_REWARDS =
  "SET_SELECTED_SECTION_FOR_REWARDS";

export const SET_REWARDS_LIST = "SET_REWARDS_LIST";
export const SET_REWARDS_OVERVIEW_PAGE_INDEX =
  "SET_REWARDS_OVERVIEW_PAGE_INDEX";
export const SET_REWARDS_OVERVIEW_PAGE_SIZE = "SET_REWARDS_OVERVIEW_PAGE_SIZE";
export const SET_SNACKBAR_FOR_REWARDS_OVERVIEW =
  "SET_SNACKBAR_FOR_REWARDS_OVERVIEW";

export const SET_REDEMPTION_REQUESTS_LIST = "SET_REDEMPTION_REQUESTS_LIST";
export const SET_REDEMPTION_REQUESTS_PAGE_INDEX =
  "SET_REDEMPTION_REQUESTS_PAGE_INDEX";
export const SET_REDEMPTION_REQUESTS_PAGE_SIZE =
  "SET_REDEMPTION_REQUESTS_PAGE_SIZE";
export const SET_SNACKBAR_FOR_REDEMPTION_REQUESTS =
  "SET_SNACKBAR_FOR_REDEMPTION_REQUESTS";

export const SET_REWARDS_HISTORY_LIST = "SET_REWARDS_HISTORY_LIST";
export const SET_REWARDS_HISTORY_PAGE_INDEX = "SET_REWARDS_HISTORY_PAGE_INDEX";
export const SET_REWARDS_HISTORY_PAGE_SIZE = "SET_REWARDS_HISTORY_PAGE_SIZE";
export const SET_SNACKBAR_FOR_REWARDS_HISTORY =
  "SET_SNACKBAR_FOR_REWARDS_HISTORY";

// async

export const GET_REWARDS_LIST_SAGA = "GET_REWARDS_LIST_SAGA";
export const CREATE_REWARD_SAGA = "CREATE_REWARD_SAGA";
export const UPDATE_REWARD_SAGA = "UPDATE_REWARD_SAGA";
export const DELETE_REWARD_SAGA = "DELETE_REWARD_SAGA";

export const GET_REDEMPTION_REQUESTS_LIST_SAGA =
  "GET_REDEMPTION_REQUESTS_LIST_SAGA";
export const CREATE_REDEMPTION_REQUEST_SAGA = "CREATE_REDEMPTION_REQUEST_SAGA";
export const SETTLE_REDEMPTION_REQUEST_SAGA = "SETTLE_REDEMPTION_REQUEST_SAGA";
export const DECLINE_REDEMPTION_REQUEST_SAGA =
  "DECLINE_REDEMPTION_REQUEST_SAGA";

export const GET_REWARDS_HISTORY_LIST_SAGA = "GET_REWARDS_HISTORY_LIST_SAGA";
