export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const RESET_INITIAL_AUTH_STATE = "RESET_INITIAL_AUTH_STATE";

// async

export const AUTHORIZE_SAGA = "AUTHORIZE_SAGA";
export const VALIDATE_TOKEN_SAGA = "VALIDATE_TOKEN_SAGA";
export const LOGOUT_SAGA = "LOGOUT_SAGA";
