export const SET_SELECTED_SECTION_FOR_DASHBOARD =
  "SET_SELECTED_SECTION_FOR_DASHBOARD";
export const SET_DASHBOARD_IS_LOADING = "SET_DASHBOARD_IS_LOADING";
export const RESET_INITIAL_DASHBOARD_STATE = "RESET_INITIAL_DASHBOARD_STATE";

// async
