export const CHEERSLY_TOKEN = "CHEERSLY_TOKEN";

export const CHEERSLY_SUPPORT_EMAIL = "support@cheersly.club";

export const MAX_COMPANY_VALUE_TITLE_LENGTH = 50;

export const MAX_COMPANY_VALUE_DESCRIPTION_LENGTH = 250;

export const MAX_REWARD_TITLE_LENGTH = 50;

export const MAX_REWARD_DESCRIPTION_LENGTH = 250;
