export const SET_COMPANY_VALUES_IS_LOADING = "SET_COMPANY_VALUES_IS_LOADING";
export const RESET_INITIAL_COMPANY_VALUES_STATE =
  "RESET_INITIAL_COMPANY_VALUES_STATE";
export const SET_COMPANY_VALUES_LIST = "SET_COMPANY_VALUES_LIST";

// async

export const GET_COMPANY_VALUES_LIST_SAGA = "GET_COMPANY_VALUES_LIST_SAGA";
export const CREATE_COMPANY_VALUES_SAGA = "CREATE_COMPANY_VALUES_SAGA";
export const UPDATE_COMPANY_VALUES_SAGA = "UPDATE_COMPANY_VALUES_SAGA";
export const DELETE_COMPANY_VALUES_SAGA = "DELETE_COMPANY_VALUES_SAGA";
