export const SET_LEADERBOARD_IS_LOADING = "SET_LEADERBOARD_IS_LOADING";
export const RESET_INITIAL_LEADERBOARD_STATE =
  "RESET_INITIAL_LEADERBOARD_STATE";
export const SET_LEADERBOARD_LIST = "SET_LEADERBOARD_LIST";

// async

export const GET_LEADERBOARD_LIST_SAGA = "GET_LEADERBOARD_LIST_SAGA";
