export const RESET_APP_STATE = "RESET_APP_STATE";
export const SET_TEAM_POINT_BALANCE = "SET_TEAM_POINT_BALANCE";
export const SET_USER_POINT_BALANCE = "SET_USER_POINT_BALANCE";

// async

export const GET_USER_POINT_BALANCE_SAGA = "GET_USER_POINT_BALANCE_SAGA";
export const GET_TEAM_POINT_BALANCE_SAGA = "GET_TEAM_POINT_BALANCE_SAGA";
